sudo: false
dist: trusty
language: php

php:
    - '7.1'
    - '7.2'
    - nightly

git:
    depth: 5

cache:
    directories:
    - $HOME/.composer/cache

addons:
    apt:
        packages:
        - parallel

matrix:
    fast_finish: true
    allow_failures:
    - php: nightly

before_install:
    - |
        tfold () {
            local title=$1
            local fold=$(echo $title | sed -r 's/[^-_A-Za-z0-9]+/./g')
            shift
            local id=$(printf %08x $(( RANDOM * RANDOM )))
            local start=$(date -u "+%s%N")

            echo -e "travis_fold:start:$fold"
            echo -e "travis_time:start:$id"
            echo -e "\\e[33;1m$title\\e[0m"
            bash -xc "$*" 2>&1
            local ok=$?
            local end=$(date -u "+%s%N")
            echo -e "\\ntravis_time:end:$id:start=$start,finish=$end,duration=$(($end-$start))"
            echo -e "travis_fold:end:$fold"
        }
        export -f tfold
    - wget https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.0.3.778-linux.zip && unzip sonar-scanner-cli-3.0.3.778-linux.zip
    - sonar-scanner-3.0.3.778-linux -v

install:
    - |
        run_tests() {
            set -e

            tfold a.1 \
            "echo 'HELLO ! '"
            tfold a.2 \
            "ls -d tests/Domain/* | parallel --gnu --keep-order 'echo "Running {} tests"; phpdbg -qrr phpunit -c phpunit.xml --colors=always {} || (echo -e "\e[41mFAILED\e[0m {}" && $(exit 1));'"
            tfold a.3i \
            "echo 'BYE !!!'"
        }
        export -f run_tests

before_script:
    #- phpenv config-rm xdebug.ini || echo "Xdebug not available"
    # Add composer's global bin directory to the path
    # see: https://github.com/drush-ops/drush#install---composer
    - export PATH="$HOME/.config/composer/vendor/bin:$PATH"
    - composer self-update
    - composer global require pdepend/pdepend phpmd/phpmd sebastian/phpcpd phploc/phploc squizlabs/php_codesniffer mayflower/php-codebrowser phpunit/phpunit behat/behat phpstan/phpstan phing/phing
    - composer install --no-dev --prefer-dist --ansi --no-interaction --no-suggest --no-progress --optimize-autoloader

script:
    - phpunit --coverage-clover=coverage.xml --bootstrap src/Domain/Math/Calculator.php tests/Domain/Math/CalculatorTest.php
    
after_success:
    - bash <(curl -s https://codecov.io/bash)
